In [36]:
# load library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [37]:
# load data
r2d0 = pd.read_csv('round-2-island-data-bottle/prices_round_2_day_-1.csv', sep = ';')
r2d1 = pd.read_csv('round-2-island-data-bottle/prices_round_2_day_0.csv', sep = ';')
r2d2 = pd.read_csv('round-2-island-data-bottle/prices_round_2_day_1.csv', sep = ';')

In [38]:
r2d0

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,-1,0,CROISSANTS,4304,112,NaN,NaN,NaN,NaN,4305,112,NaN,NaN,NaN,NaN,4304.5,0.0
1,-1,0,JAMS,6670,66,6669.0,137.0,NaN,NaN,6671,66,6672.0,137.0,NaN,NaN,6670.5,0.0
2,-1,0,SQUID_INK,2005,1,2002.0,31.0,NaN,NaN,2006,31,NaN,NaN,NaN,NaN,2005.5,0.0
3,-1,0,PICNIC_BASKET1,59284,20,59283.0,18.0,NaN,NaN,59294,2,59295.0,36.0,NaN,NaN,59289.0,0.0
4,-1,0,PICNIC_BASKET2,30606,20,30605.0,18.0,NaN,NaN,30612,20,30613.0,18.0,NaN,NaN,30609.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,-1,999900,DJEMBES,13493,76,NaN,NaN,NaN,NaN,13494,76,NaN,NaN,NaN,NaN,13493.5,0.0
79996,-1,999900,KELP,2028,31,NaN,NaN,NaN,NaN,2030,6,2031.0,31.0,NaN,NaN,2029.0,0.0
79997,-1,999900,RAINFOREST_RESIN,9992,32,NaN,NaN,NaN,NaN,10008,32,NaN,NaN,NaN,NaN,10000.0,0.0
79998,-1,999900,PICNIC_BASKET1,59222,2,59221.0,13.0,59220.0,27.0,59231,2,59232.0,13.0,59233.0,27.0,59226.5,0.0
79999,-1,999900,PICNIC_BASKET2,30502,15,30501.0,27.0,NaN,NaN,30507,2,30508.0,40.0,NaN,NaN,30504.5,0.0

In [39]:
def update_timestamp(df):
    df['timestamp'] = df['day']*100*10000+df['timestamp']
    df.drop(['day'], axis = 1, inplace = True)
    return df

In [40]:
r2d0_shift = update_timestamp(r2d0)
r2d1_shift = update_timestamp(r2d1)
r2d2_shift = update_timestamp(r2d2)

In [41]:
r2d0

,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,-1000000,CROISSANTS,4304,112,NaN,NaN,NaN,NaN,4305,112,NaN,NaN,NaN,NaN,4304.5,0.0
1,-1000000,JAMS,6670,66,6669.0,137.0,NaN,NaN,6671,66,6672.0,137.0,NaN,NaN,6670.5,0.0
2,-1000000,SQUID_INK,2005,1,2002.0,31.0,NaN,NaN,2006,31,NaN,NaN,NaN,NaN,2005.5,0.0
3,-1000000,PICNIC_BASKET1,59284,20,59283.0,18.0,NaN,NaN,59294,2,59295.0,36.0,NaN,NaN,59289.0,0.0
4,-1000000,PICNIC_BASKET2,30606,20,30605.0,18.0,NaN,NaN,30612,20,30613.0,18.0,NaN,NaN,30609.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,-100,DJEMBES,13493,76,NaN,NaN,NaN,NaN,13494,76,NaN,NaN,NaN,NaN,13493.5,0.0
79996,-100,KELP,2028,31,NaN,NaN,NaN,NaN,2030,6,2031.0,31.0,NaN,NaN,2029.0,0.0
79997,-100,RAINFOREST_RESIN,9992,32,NaN,NaN,NaN,NaN,10008,32,NaN,NaN,NaN,NaN,10000.0,0.0
79998,-100,PICNIC_BASKET1,59222,2,59221.0,13.0,59220.0,27.0,59231,2,59232.0,13.0,59233.0,27.0,59226.5,0.0
79999,-100,PICNIC_BASKET2,30502,15,30501.0,27.0,NaN,NaN,30507,2,30508.0,40.0,NaN,NaN,30504.5,0.0

In [42]:
# merge the three dataframes into one
r2 = pd.concat([r2d0_shift, r2d1_shift, r2d2_shift], axis = 0)

In [43]:
for i in r2['product'].unique():
    print(i)

CROISSANTS
JAMS
SQUID_INK
PICNIC_BASKET1
PICNIC_BASKET2
RAINFOREST_RESIN
DJEMBES
KELP

In [44]:
r2_CROISSANTS = r2[r2['product']=='CROISSANTS'].copy()
r2_JAMS = r2[r2['product']=='JAMS'].copy()
r2_SQUID_INK = r2[r2['product']=='SQUID_INK'].copy()
r2_PICNIC_BASKET1 = r2[r2['product']=='PICNIC_BASKET1'].copy()
r2_PICNIC_BASKET2 = r2[r2['product']=='PICNIC_BASKET2'].copy()
r2_RAINFOREST_RESIN = r2[r2['product']=='RAINFOREST_RESIN'].copy()
r2_DJEMBES = r2[r2['product']=='DJEMBES'].copy()
r2_KELP = r2[r2['product']=='KELP'].copy()

In [45]:
r2_CROISSANTS.head(5)

,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,-1000000,CROISSANTS,4304,112,NaN,NaN,NaN,NaN,4305,112,NaN,NaN,NaN,NaN,4304.5,0.0
12,-999900,CROISSANTS,4304,133,NaN,NaN,NaN,NaN,4305,133,NaN,NaN,NaN,NaN,4304.5,0.0
19,-999800,CROISSANTS,4304,110,NaN,NaN,NaN,NaN,4305,110,NaN,NaN,NaN,NaN,4304.5,0.0
30,-999700,CROISSANTS,4304,118,NaN,NaN,NaN,NaN,4305,118,NaN,NaN,NaN,NaN,4304.5,0.0
33,-999600,CROISSANTS,4305,142,NaN,NaN,NaN,NaN,4306,142,NaN,NaN,NaN,NaN,4305.5,0.0

In [57]:
def get_df(df):
    df = df[['timestamp', 'product', 'mid_price', 'bid_price_1', 'ask_price_1', 'bid_volume_1', 'ask_volume_1']].copy()
    df['mid_price'] = df['mid_price'].astype(float)
    df['bid_price_1'] = df['bid_price_1'].astype(float)
    df['ask_price_1'] = df['ask_price_1'].astype(float)
    df['bid_volume_1'] = df['bid_volume_1'].astype(float)
    df['ask_volume_1'] = df['ask_volume_1'].astype(float)

    df['imb'] = df['bid_volume_1'].astype(float)/(df['bid_volume_1'].astype(float)+df['ask_volume_1'].astype(float))
    df['wmid'] = df['ask_price_1'].astype(float)*df['imb']+df['bid_price_1'].astype(float)*(1-df['imb'])
    # df.rename(columns = {'mid_price':'mid', 'bid_price_1':'bid', 'ask_price_1':'ask', 'bid_volume_1':'bs', 'ask_volume_1':'as','timestamp':'time'}, inplace = True)
    return df.reset_index(drop = True)

In [47]:
from scipy.linalg import block_diag

In [48]:
r2_CROISSANTS.head()

,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,-1000000,CROISSANTS,4304,112,NaN,NaN,NaN,NaN,4305,112,NaN,NaN,NaN,NaN,4304.5,0.0
12,-999900,CROISSANTS,4304,133,NaN,NaN,NaN,NaN,4305,133,NaN,NaN,NaN,NaN,4304.5,0.0
19,-999800,CROISSANTS,4304,110,NaN,NaN,NaN,NaN,4305,110,NaN,NaN,NaN,NaN,4304.5,0.0
30,-999700,CROISSANTS,4304,118,NaN,NaN,NaN,NaN,4305,118,NaN,NaN,NaN,NaN,4304.5,0.0
33,-999600,CROISSANTS,4305,142,NaN,NaN,NaN,NaN,4306,142,NaN,NaN,NaN,NaN,4305.5,0.0

In [49]:
def prep_data_sym(T, n_imb, dt, n_spread):
    # Rename for compatibility with original function
    T = T.copy()
    T['bid'] = T['bid_price_1']
    T['ask'] = T['ask_price_1']
    T['bs'] = T['bid_volume_1']
    T['as'] = T['ask_volume_1']
    T['time'] = T['timestamp']  # Optional: modify if needed

    # Compute spread and tick size
    spread = T['ask'] - T['bid']
    ticksize = np.round(min(spread[spread > 0]) * 100) / 100

    # Add spread and mid price
    T['spread'] = np.round((T['ask'] - T['bid']) / ticksize) * ticksize
    T['mid'] = (T['bid'] + T['ask']) / 2

    # Filter out large spreads
    T = T.loc[(T['spread'] <= n_spread * ticksize) & (T['spread'] > 0)]

    # Compute imbalance and discretize
    T['imb'] = T['bs'] / (T['bs'] + T['as'])
    T['imb_bucket'] = pd.qcut(T['imb'], n_imb, labels=False, duplicates='drop')
    # Step ahead variables
    T['next_mid'] = T['mid'].shift(-dt)
    T['next_spread'] = T['spread'].shift(-dt)
    T['next_time'] = T['time'].shift(-dt)
    T['next_imb_bucket'] = T['imb_bucket'].shift(-dt)

    # Change in mid price
    T['dM'] = np.round((T['next_mid'] - T['mid']) / ticksize * 2) * ticksize / 2

    # Filter abnormal price changes
    T = T.loc[(T['dM'] <= ticksize * 1.1) & (T['dM'] >= -ticksize * 1.1)]

    # Symmetrize
    T2 = T.copy(deep=True)
    T2['imb_bucket'] = n_imb - 1 - T2['imb_bucket']
    T2['next_imb_bucket'] = n_imb - 1 - T2['next_imb_bucket']
    T2['dM'] = -T2['dM']
    T2['mid'] = -T2['mid']

    T3 = pd.concat([T, T2])
    T3.index = pd.RangeIndex(len(T3.index))

    return T3, ticksize

In [53]:
T1,ticksize1 = prep_data_sym(r2_CROISSANTS, n_imb=10, dt = 1, n_spread = 2)
T2,ticksize2 = prep_data_sym(r2_JAMS, n_imb=10, dt = 1, n_spread = 2)
T3,ticksize3 = prep_data_sym(r2_SQUID_INK, n_imb=10, dt = 1, n_spread = 2)
T4,ticksize4 = prep_data_sym(r2_PICNIC_BASKET1, n_imb=10, dt = 1, n_spread = 2)
T5,ticksize5 = prep_data_sym(r2_PICNIC_BASKET2, n_imb=10, dt = 1, n_spread = 2)
T6,ticksize6 = prep_data_sym(r2_RAINFOREST_RESIN, n_imb=10, dt = 1, n_spread = 2)
T7,ticksize7 = prep_data_sym(r2_DJEMBES, n_imb=10, dt = 1, n_spread = 2)
T8,ticksize8 = prep_data_sym(r2_KELP, n_imb=10, dt = 1, n_spread = 2)

In [50]:
def estimate(T, n_imb, n_spread):
    # Q matrix: transition counts where dM == 0 (no price move)
    no_move = T[T['dM'] == 0]
    no_move_counts = no_move.pivot_table(
        index=['next_imb_bucket'],
        columns=['spread', 'imb_bucket'],
        values='time',
        fill_value=0,
        aggfunc='count'
    ).unstack().fillna(0)

    # Convert pivot table to matrix format
    Q_counts = no_move_counts.values[:n_imb * n_imb].reshape(n_imb, n_imb)

    # Add more blocks if multiple spreads exist
    for i in range(1, n_spread):
        start = i * n_imb * n_imb
        end = (i + 1) * n_imb * n_imb
        if end > len(no_move_counts):
            break
        Qi = no_move_counts.values[start:end].reshape(n_imb, n_imb)
        Q_counts = block_diag(Q_counts, Qi)

    # R1 matrix: transitions where dM ≠ 0 (price moved)
    move = T[T['dM'] != 0]
    move_counts = move.pivot_table(
        index=['dM'],
        columns=['spread', 'imb_bucket'],
        values='time',
        fill_value=0,
        aggfunc='count'
    ).unstack().fillna(0)

    R_counts = move_counts.values.reshape(n_imb * n_spread, 4)

    # Normalize transition matrix (Q + R1)
    T1 = np.concatenate((Q_counts, R_counts), axis=1).astype(float)
    for i in range(T1.shape[0]):
        row_sum = T1[i].sum()
        if row_sum > 0:
            T1[i] = T1[i] / row_sum

    Q = T1[:, :n_imb * n_spread]
    R1 = T1[:, n_imb * n_spread:]

    # Reward vector
    K = np.array([-0.01, -0.005, 0.005, 0.01])

    # R2 matrix: (next_spread, next_imb_bucket) transitions for spread/imb states
    move_counts_2 = move.pivot_table(
        index=['spread', 'imb_bucket'],
        columns=['next_spread', 'next_imb_bucket'],
        values='time',
        fill_value=0,
        aggfunc='count'
    ).fillna(0)

    R2_counts = move_counts_2.values.reshape(n_imb * n_spread, n_imb * n_spread)

    T2 = np.concatenate((Q_counts, R2_counts), axis=1).astype(float)
    for i in range(T2.shape[0]):
        row_sum = T2[i].sum()
        if row_sum > 0:
            T2[i] = T2[i] / row_sum

    Q2 = T2[:, :n_imb * n_spread]
    R2 = T2[:, n_imb * n_spread:]

    # Expected gain vector (G1) and transition matrix (B)
    I = np.eye(n_imb * n_spread)
    G1 = np.dot(np.dot(np.linalg.inv(I - Q), R1), K)
    B = np.dot(np.linalg.inv(I - Q), R2)

    return G1, B, Q, Q2, R1, R2, K

In [51]:
def plot_Gstar(ticker, G1, B, T, n_imb=10, n_spread=2):
    # Compute long-term expected gain G*
    G = G1.copy()
    for _ in range(5):
        G = G + B @ G

    # x-axis: imbalance bucket centers
    imb_bucket_centers = np.linspace(0, 1, n_imb)

    plt.figure(figsize=(10, 6))
    
    # Optional baseline comparisons (dashed lines)
    plt.plot(imb_bucket_centers, np.zeros(n_imb), label='Mid adj (0)', linestyle='--', color='gray')
    plt.plot(imb_bucket_centers, np.linspace(-0.005, 0.005, n_imb), label='Weighted mid adj', linestyle='--', color='lightblue')

    # Plot each spread level
    for i in range(n_spread):
        adj = G[i * n_imb : (i + 1) * n_imb]
        plt.plot(imb_bucket_centers, adj, label=f"Spread = {i + 1} tick adj", marker='o')

    plt.ylim(-0.005, 0.005)
    plt.xlabel("Order Book Imbalance")
    plt.ylabel("Expected Price Adjustment")
    plt.title(f"{ticker} - Long-term Gain G* by Spread & Imbalance")
    plt.legend(loc='upper left')
    plt.grid(True)
    plt.show()

    return G

In [ ]:
n_imb = 10
n_spread = 2
dt = 1
data = get_df(r2_CROISSANTS)
ticker = 'BANANAS'

pd.set_option('mode.chained_assignment', None)
import warnings
warnings.simplefilter(action='ignore', category=UserWarning)

In [62]:
imb_bucket_centers = np.linspace(0, 1, n_imb)
G1, B, Q, Q2, R1, R2, K = estimate(T1, n_imb=n_imb, n_spread=n_spread)
G6 = plot_Gstar(ticker, G1, B, T1, n_imb=n_imb, n_spread=n_spread)

ValueError: cannot reshape array of size 56 into shape (20,4)

In [ ]:
W=np.linalg.matrix_power(B,100)
for i in range(0,n_spread):
    plt.plot(imb,W[0][(0+i*n_imb):(n_imb+i*n_imb)],label="spread = "+str(i+1)+" tick ",marker='o')
    
plt.legend(loc='upper left')
plt.title('stationary distribution')
plt.xlabel('Imbalance')

In [ ]:
G6

In [ ]:
n_imb=4
n_spread=4
dt=1
data=get_df(r2_pearls) 
ticker='PEARLS'
T,ticksize=prep_data_sym(data,n_imb,dt,n_spread)
imb=np.linspace(0,1,n_imb)
G1,B,Q,Q2,R1,R2,K=estimate(T)

In [ ]:
G6=plot_Gstar(ticker,G1,B,T)

In [ ]:
W=np.linalg.matrix_power(B,100)
for i in range(0,n_spread):
    plt.plot(imb,W[0][(0+i*n_imb):(n_imb+i*n_imb)],label="spread = "+str(i+1)+" tick ",marker='o')
    
plt.legend(loc='upper left')
plt.title('stationary distribution')
plt.xlabel('Imbalance')